### ISSUE TITLE
Criar função para salvar dados pessoais do profissional

### ISSUE THREAD

**Issue by Guilherme-Jorge** [Guilherme-Jorge/DenTeethAPI#3]
Função deve salvar nome, telefone, email, no máximo 3 endereços e um currículo.

Nome, telefone, email, um endereço e o currículo devem ser obrigatórios, então exigir na função estes 3 parâmetros.

**Comment by jparrigo** [comment]
#4

**Comment by Guilherme-Jorge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[API] Subir informações da criação da conta para o Firebase - Sprint 1](https://trello.com/c/BLFRHxaA/3-api-subir-informa%C3%A7%C3%B5es-da-cria%C3%A7%C3%A3o-da-conta-para-o-firebase-sprint-1)
